# Codespell configuration is within .codespellrc
name: Lint and Spellcheck

on:
    push:
      branches: 
        - '**'
    pull_request:
      branches: [main]

permissions:
    contents: read

jobs:
  lintandspell:
    name: Check for spelling and formatting errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Annotate locations with typos
        uses: codespell-project/codespell-problem-matcher@v1

      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
            exclude_file: poetry.lock
      
      - name: Lint files with Black
        run: make check-black
